# Generated by Django 5.2.8 on 2025-11-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('TECH', 'Tech'), ('LIFE', 'Lifestyle'), ('NEWS', 'News'), ('GLOBAL', 'Global')], default='GLOBAL', max_length=20),
        ),
    ]
